version: "3.9"
   
services:
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: sisacad_db
    environment:
      - POSTGRES_DB=postgres2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


  backend:
    build: ./backend
    container_name: sisacad_backend
    command: python manage.py runserver --settings=core.settings.dev  0.0.0.0:8000
    #volumes:
    #  - .:/backend/sistema_academico
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: sisacad_frontend
    command: npm run serve
    ports:
      - "8080:8080"

      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: sisacad_portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000



volumes:
  postgres_data:

